version: '3.3'
services:
  engine:
    container_name: ${PROJECT_NAME}_engine
    build:
      context: ./src/engine
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./src/engine:/code
    ports:
      - "18002:80"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    container_name: ${PROJECT_NAME}_db
    ports:
      - '10905:5432'
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/dumps:/dumps
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  nodejs-server:
    build:
      context: ./src/front/api
      dockerfile: Dockerfile-dev
    ports:
      - "3080:3080"
    container_name: node-api
    volumes:
       - ./src/front/:/usr/src/app/api
       - /usr/src/app/api/node_modules
       
  vue-ui:
    build:
      context: ./src/front/my-app
      dockerfile: Dockerfile-dev
    ports:
      - "8080:8080"
    container_name: vue-ui
    volumes:
       - ./src/front/my-app:/usr/src/app/my-app
       - /usr/src/app/my-app/node_modules