version: '3.3'
services:
  engine:
    container_name: ${PROJECT_NAME}_engine
    build:
      context: ./src/engine
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./src/engine:/code
    ports:
      - "18002:80"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    container_name: ${PROJECT_NAME}_db
    ports:
      - '10905:5432'
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/dumps:/dumps
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"